<?php

/**
 * @file
 * Install and update functions for the OE Pwbi module.
 */

declare(strict_types=1);

use Drupal\oe_bootstrap_theme\ConfigImporter;

/**
 * Implements hook_install().
 *
 * Imports configuration on module install.
 */
function oe_showcase_pwbi_install(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  ConfigImporter::importSingle('module', 'oe_showcase_pwbi', '/config/overrides/', 'field.field.node.oe_showcase_page.field_body');
}
