clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_showcase

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    environment:
      - DOCUMENT_ROOT=/test/oe_showcase
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
  sparql:
    image: registry.fpfis.eu/openeuropa/triple-store-dev
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.59-oxygen
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

pipeline:
  build-branch:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-progress
    when:
      matrix:
        TYPE: install

  build-release:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    volumes:
      - /cache:/cache
    commands:
      - git config --global --add safe.directory /test/oe_showcase
      - git fetch --tags
      - git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
      - composer install --ansi --no-progress
    when:
      matrix:
        TYPE: update

  install-branch:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - while ! mysqladmin ping -h mysql --silent; do sleep 1; done
      - ./vendor/bin/run drupal:site-install
    when:
      matrix:
        TYPE: install

  install-release:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - while ! mysqladmin ping -h mysql --silent; do sleep 1; done
      - ./vendor/bin/run drupal:site-install
    when:
      matrix:
        TYPE: update

  switch-branch:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - git config --global --add safe.directory /test/oe_showcase
      - git checkout ${DRONE_BRANCH}
      - rm -Rf vendor
      - composer install --ansi --no-progress
    when:
      matrix:
        TYPE: update

  update-branch:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - ./vendor/bin/drush updb -y
      - ./vendor/bin/drush cr
    when:
      matrix:
        TYPE: update

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - ./vendor/bin/run ci:site-setup
      - ./vendor/bin/drush en -y media_avportal_mock oe_media_oembed_mock
      - ./vendor/bin/phpunit

matrix:
  TYPE:
    - install
    - update
