clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_showcase

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - DOCUMENT_ROOT=/test/oe_showcase
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
  sparql:
    image: registry.fpfis.eu/openeuropa/triple-store-dev
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.59-oxygen
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

pipeline:
  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer self-update --1
      - composer install --ansi --no-suggest --no-progress

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/run drupal:site-install
    when:
      event:
        exclude: tag

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run
    when:
      event:
        exclude: tag

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit
    when:
      event:
        exclude: tag

matrix:
  PHP_VERSION:
    - 7.4
