<?php

/**
 * @file
 * OE Showcase Contact forms module.
 */

declare(strict_types=1);

use Drupal\symfony_mailer\Address;
use Drupal\symfony_mailer\EmailInterface;

/**
 * Implements hook_mailer_TYPE_PHASE().
 */
function oe_showcase_contact_forms_mailer_contact_build(EmailInterface $email) {
  if (empty($email->getTo())) {
    return;
  }
  // 1. Module contact from Drupal Core implodes all the recipients with ', ' in
  // mails when the message is not personal and has multiple recipients.
  // @see \Drupal/contact/MailHandler::sendMailMessages()
  // 2. Module symfony_mailer provides a parser to explode all the recipients
  // without having in consideration any extra spaces which sets addresses like
  // ' test@mail.com'.
  // @see \Drupal\symfony_mailer\MailerHelper::parseAddress()
  $addresses = [];
  foreach ($email->getTo() as $address) {
    $addresses[] = new Address(trim($address->getEmail()), $address->getDisplayName(), $address->getLangcode(), $address->getAccount());
  }
  $email->setTo($addresses);
}
