<?php

/**
 * @file
 * Showcase user profile module.
 */

declare(strict_types = 1);

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\image\Plugin\Field\FieldType\ImageItem;
use Drupal\oe_bootstrap_theme\ValueObject\ImageValueObject;
use Drupal\user\Entity\User;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function oe_showcase_user_profile_theme_suggestions_user_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'user__' . $variables['elements']['#view_mode'];
}

/**
 * Implements hook_theme().
 */
function oe_showcase_user_profile_theme() {
  return [
    'user__full' => [
      'render element' => 'elements',
      'base hook' => 'user',
    ],
    'user__teaser' => [
      'render element' => 'elements',
      'base hook' => 'user',
    ],
  ];
}

/**
 * Implements hook_user_format_name_alter().
 */
function oe_showcase_user_profile_user_format_name_alter(string &$name, AccountInterface $account) {
  if (!$account instanceof User) {
    return;
  }
  $username = [];
  if (!$account->get('field_first_name')->isEmpty()) {
    $username[] = $account->get('field_first_name')->value;
  }
  if (!$account->get('field_last_name')->isEmpty()) {
    $username[] = $account->get('field_last_name')->value;
  }
  if (empty($username)) {
    return;
  }
  $name = implode(' ', $username);
}

/**
 * Implements hook_form_FORM_ID_alter() for the user form.
 */
function oe_showcase_user_profile_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $field_names = [
    'field_first_name',
    'field_last_name',
    'field_organization',
  ];
  foreach ($field_names as $field_name) {
    $form[$field_name]['widget'][0]['value']['#disabled'] = TRUE;
    // Don't overwrite existing description.
    $description = $form[$field_name]['widget'][0]['value']['#description'] ?? '';
    $text = t('This value is coming from ECAS and cannot be changed here.');
    $form[$field_name]['widget'][0]['value']['#description'] = ($description !== '')
      ? $description . '<br/>' . $text
      : $text;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_showcase_user_profile_preprocess_user__full(array &$variables): void {
  /** @var \Drupal\user\UserInterface $user */
  $user = $variables['user'];
  $image_item_list = $user->get('field_profile_image');
  $image_item = $image_item_list->get(0);
  if (!$image_item instanceof ImageItem || !$image_item_list->access()) {
    // No profile image found, or no view access.
    return;
  }
  $variables['pattern_image'] = ImageValueObject::fromStyledImageItem($image_item, 'medium');
  // Get cache info from the render element instead of the image item.
  // This assumes that the image field display is configured exactly as in
  // config/install/core.entity_view_display.user.user.full.yml in this module.
  // @todo Once OEL-1166 is fixed in oe_bootstrap_theme, get cache info directly
  //   from the ImageValueObject, and hide the image field in field ui.
  $cacheability = CacheableMetadata::createFromRenderArray($variables['elements']['field_profile_image'][0]);
  $cacheability->applyTo($variables);
}
