<?php

/**
 * @file
 * Showcase user profile module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\image\Plugin\Field\FieldType\ImageItem;
use Drupal\oe_bootstrap_theme\ValueObject\ImageValueObject;
use Drupal\user\Entity\User;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function oe_showcase_user_profile_theme_suggestions_user_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'user__' . $variables['elements']['#view_mode'];
}

/**
 * Implements hook_theme().
 */
function oe_showcase_user_profile_theme() {
  return [
    'user__full' => [
      'render element' => 'elements',
      'base hook' => 'user',
    ],
    'user__teaser' => [
      'render element' => 'elements',
      'base hook' => 'user',
    ],
  ];
}

/**
 * Implements hook_user_format_name_alter().
 */
function oe_showcase_user_profile_user_format_name_alter(string &$name, AccountInterface $account) {
  if (!$account instanceof User) {
    return;
  }
  $username = [];
  if (!$account->get('field_first_name')->isEmpty()) {
    $username[] = $account->get('field_first_name')->value;
  }
  if (!$account->get('field_last_name')->isEmpty()) {
    $username[] = $account->get('field_last_name')->value;
  }
  if (empty($username)) {
    return;
  }
  $name = implode(' ', $username);
}

/**
 * Implements hook_form_FORM_ID_alter() for the user form.
 */
function oe_showcase_user_profile_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $field_names = [
    'field_first_name',
    'field_last_name',
    'field_organization',
  ];
  foreach ($field_names as $field_name) {
    $form[$field_name]['widget'][0]['value']['#disabled'] = TRUE;
    // Don't overwrite existing description.
    $description = $form[$field_name]['widget'][0]['value']['#description'] ?? '';
    $text = t('This value is coming from ECAS and cannot be changed here.');
    $form[$field_name]['widget'][0]['value']['#description'] = ($description !== '')
      ? $description . '<br/>' . $text
      : $text;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_showcase_user_profile_preprocess_user__full(array &$variables): void {
  // Set an image value object for the header banner pattern.
  $image_element = $variables['elements']['field_profile_image'][0] ?? NULL;
  $variables['pattern_image'] = NULL;
  if ($image_element !== NULL) {
    $image_item = $image_element['#item'] ?? NULL;
    if ($image_item instanceof ImageItem) {
      $variables['pattern_image'] = isset($image_element['#image_style'])
        ? ImageValueObject::fromStyledImageItem($image_item, $image_element['#image_style'])
        : ImageValueObject::fromImageItem($image_item);
    }
  }
}
