<?php

/**
 * @file
 * Showcase search module.
 */

declare(strict_types =  1);

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\oe_bootstrap_theme\ValueObject\ImageValueObject;

/**
 * Implements hook_theme().
 */
function oe_showcase_search_theme() {
  return [
    'node__search_result' => [
      'render element' => 'elements',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_node() for 'search_result' view mode.
 *
 * Prepares the image value object for the card pattern.
 *
 * Note that, like the template, this preprocess function does not target a
 * specific node type. This is ok because currently only one node type uses the
 * 'search_result' view mode.
 */
function oe_showcase_search_preprocess_node__search_result(array &$variables): void {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];
  $image_item_list = $node->get('field_image');
  if ($image_item_list->isEmpty() || !$image_item_list->access()) {
    // No image, or no view access.
    return;
  }
  /** @var \Drupal\image\Plugin\Field\FieldType\ImageItem $image_item */
  $image_item = $image_item_list->get(0);
  $variables['image'] = ImageValueObject::fromStyledImageItem($image_item, 'medium');
  CacheableMetadata::createFromObject($variables['image'])
    ->applyTo($variables);
}
