<?php

/**
 * @file
 * Install and update functions for the OE Showcase Navigation module.
 */

declare(strict_types=1);

use Drupal\oe_bootstrap_theme\ConfigImporter;

/**
 * Implements hook_install().
 *
 * Imports configuration on module install.
 */
function oe_showcase_navigation_install(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  $configs = [
    'oe_corporate_blocks.footer_link.general.about_us',
    'oe_corporate_blocks.footer_link.general.contact_us',
  ];

  ConfigImporter::importMultiple('module', 'oe_showcase_navigation', '/config/overrides/', $configs);

  // Override changes from oe_corporate_blocks.
  $config = [
    'oe_corporate_blocks.footer_link.general.events',
    'oe_corporate_blocks.footer_link.general.funding_and_tenders',
    'oe_corporate_blocks.footer_link.general.jobs',
    'oe_corporate_blocks.footer_link.general.press_corner',
    'oe_corporate_blocks.footer_link.general.priorities',
    'oe_corporate_blocks.footer_link.general.topics',
    'oe_corporate_blocks.footer_link.section.ec_core_column',
  ];
  foreach ($config as $item) {
    \Drupal::configFactory()->getEditable($item)?->delete();
  }
}
