<?php

/**
 * @file
 * Install and update functions for the OE Showcase Navigation module.
 */

declare(strict_types=1);

use Drupal\oe_bootstrap_theme\ConfigImporter;

/**
 * Implements hook_install().
 *
 * Imports configuration on module install.
 */
function oe_showcase_navigation_install(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  $configs = [
    'oe_corporate_blocks.footer_link.general.about_us',
    'oe_corporate_blocks.footer_link.general.contact_us',
  ];

  ConfigImporter::importMultiple('module', 'oe_showcase_navigation', '/config/overrides/', $configs);
}
