name: ci
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - 1.x

jobs:
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          - update
          #- install
    env:
      PHP_VERSION: 8.3
    steps:
      - name: Clone repository (install)
        if: ${{ matrix.type != 'update' }}
        uses: actions/checkout@v2

      - name: Clone repository (update)
        if: ${{ matrix.type == 'update' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Checkout older version (update only)
        if: ${{ matrix.type == 'update' }}
        run: |
          git tag -f CURRENT
          git fetch --tags
          git log --graph --decorate --pretty=oneline --abbrev-commit --abbrev=8
          git status
          LATEST_TAG=$(git describe --abbrev=0 --tags --match=[1-9]*.[0-9]*.[0-9]*)
          echo "Latest tag: $LATEST_TAG"
          # Mark the current commit with a tag.
          git checkout $LATEST_TAG

      - name: Modify docker-compose.yml
        run: |
          # Replace -dev with -ci.
          sed -i 's/httpd-php:8\.3-\(dev\|ci\)/httpd-php:8.3-ci/g' docker-compose.yml
          # Remove COMPOSERVER, which may be present in the older version we checked out.
          # See https://git.fpfis.tech.ec.europa.eu/digit/devsecops/httpd-php/-/issues/3.
          sed -i '/COMPOSERVER/d' docker-compose.yml
          # Report the difference.
          git diff

      - name: docker compose up -d
        run: |
          exec 2>&1  # avoid unsynced stderr vs stdout
          set -x
          docker compose up -d
          date +"%T.%N"

      - name: composer self-update
        run: |
          exec 2>&1  # avoid unsynced stderr vs stdout
          set -x
          date +"%T.%N"
          docker compose exec -T web composer --version
          docker compose exec -T web composer self-update
          docker compose exec -T web composer --version
